apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: churn-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/luba117/ai-concern-predictions-mlops.git
    targetRevision: main
    path: churn-api
  destination:
    server: https://kubernetes.default.svc
    namespace: churn-dev