replicaCount: 3

image:
  repository: churnmlops5624.azurecr.io/churn-api
  tag: ""
  pullPolicy: IfNotPresent

decisionThreshold: "0.3"

extraEnv:
  - name: LOG_LEVEL
    value: "info"
  - name: REGION
    value: "eastus"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"

ingress:
  enabled: false

service:
  type: ClusterIP
  annotations: {}
  loadBalancerSourceRanges: []
